from tkinter import *
from .Keyboard import Keyboard

class MainWindow(Tk):
    def __init__(self):
        super().__init__()
        self.title('Calculadora de Integrales')
        self.resizable(False, False)
        self.geometry('500x400')
        self.configure(background="white")
        self.columnconfigure(index=0, weight=1)
        self.columnconfigure(index=1, weight=1)
        self.columnconfigure(index=2, weight=1)
        self.columnconfigure(index=3, weight=1)
        self.rowconfigure(index=0, weight=1)
        self.rowconfigure(index=1, weight=1)
        self.rowconfigure(index=2, weight=1)
        self.rowconfigure(index=3, weight=1)
        self.rowconfigure(index=4, weight=1)
        self.integrateSymbol = Label(self, text="∫ f(x) =", bg="white", fg="black", font=("Arial", 10, "bold"))
        self.integrateSymbol.grid(row=1, column=0, padx=5, pady=5, sticky=EW)
        self.function = Entry(self)
        self.function.grid(row=1, column=1, padx=5, pady=5, sticky=W)
        self.difSymbol = Label(self, text="d", bg="white", fg="black", font=("Arial", 10, "bold"))
        self.difSymbol.grid(row=1, column=2, padx=5, pady=5, sticky=EW)
        self.dif = Entry(self)
        self.dif.grid(row=1, column=3, padx=5, pady=5, sticky=W)
        self.bLabel = Label(self, text="b =", bg="white", fg="black", font=("Arial", 10, "bold"))
        self.bLabel.grid(row=0, column=0, padx=5, pady=5, sticky=EW)
        self.aLabel = Label(self, text="a =", bg="white", fg="black", font=("Arial", 10, "bold"))
        self.aLabel.grid(row=2, column=0, padx=5, pady=5, sticky=EW)
        self.a = Entry(self)
        self.a.grid(row=2, column=1, padx=5, pady=5, sticky=W)
        self.b = Entry(self)
        self.b.grid(row=0, column=1, padx=5, pady=5, sticky=W)
        self.result = Label(self, text="Resultado", bg="white", fg="black", font=("Arial", 10, "bold"))
        self.result.grid(row=3, column=0, columnspan=4, sticky=NSEW)
        self.keyboard = Keyboard(self.function, self.dif, self.a, self.b, self.result)
        self.keyboard.grid(row=4, column=0, columnspan=4, sticky=NSEW)